# Generated by Django 3.0 on 2019-12-06 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0002_auto_20191205_1312'),
    ]

    operations = [
        migrations.AddField(
            model_name='snippet',
            name='username',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
    ]
