# Generated by Django 2.0.12 on 2019-12-09 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0002_qn_sn'),
    ]

    operations = [
        migrations.CreateModel(
            name='results',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('regis', models.CharField(max_length=100)),
                ('marks', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['created'],
            },
        ),
        migrations.AlterField(
            model_name='questions',
            name='catagory',
            field=models.CharField(choices=[('recur1', 'IoThinC Recuirtment'), ('recur2', 'IoThinc Recuirtment2')], max_length=20),
        ),
    ]
