# Generated by Django 3.0 on 2019-12-08 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_auto_20191208_1355'),
    ]

    operations = [
        migrations.CreateModel(
            name='QN',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('q_id', models.IntegerField()),
                ('question', models.CharField(max_length=1000)),
                ('o1', models.CharField(max_length=200)),
                ('o2', models.CharField(max_length=200)),
                ('o3', models.CharField(max_length=200)),
                ('o4', models.CharField(max_length=200)),
                ('co', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ['created'],
            },
        ),
    ]
