# Generated by Django 2.0.12 on 2019-12-08 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_qn'),
    ]

    operations = [
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=250)),
                ('optiona', models.CharField(max_length=100)),
                ('optionb', models.CharField(max_length=100)),
                ('optionc', models.CharField(max_length=100)),
                ('optiond', models.CharField(max_length=100)),
                ('answer', models.CharField(max_length=100)),
                ('catagory', models.CharField(choices=[('recur_1', 'recur_1'), ('recur_2', 'recur_2'), ('recur_3', 'recur_3'), ('recur_4', 'recur_4')], max_length=20)),
            ],
            options={
                'ordering': ('-catagory',),
            },
        ),
    ]
